# Reload config file after any modification to see the changes on the notebook

SETUP:
  DATA_PATH: '../Datasets/pixelated_detector/20220715_183031/8 C2=150 a=60mrad.mib' #6
#  DATA_PATH: '../Datasets/pixelated_detector/20220727_155412/4 C2=150 deg=+20.mib' #5
#  DATA_PATH: '../Datasets/pixelated_detector/20220727_152148/3 C2=150 deg=+15.mib' #4
#  DATA_PATH: '../Datasets/pixelated_detector/20220727_162008/5 C2=150 deg=+30.mib' #3
#  DATA_PATH: '../Datasets/pixelated_detector/20220727_145218/2 C2=150 deg=-10.mib' #1
#  DATA_PATH: '../Datasets/pixelated_detector/20220715_183031/8 C2=150 a=60mrad.mib'
#  DATA_PATH: '../Datasets/pixelated_detector/20220727_135309/1 C2=150 deg=0.mib' #2
#  DATA_PATH: '../Datasets/pixelated_detector/1 C2=70.mib'

  DATA_SHAPE: [ 640,641 ] # (The shape mux include the flyback pixel in the y dimension )
  CALIB_DATA_PATH: '../../Gulnaz_Ganeeva/Pixelated detector/22-07-15/20220715_163116/2 C2=70 vacuum.mib'
  SEMIANGLE: 28 # Semiangle in mrads
  PATTERN_CALIBRATED: True
  CAlIB_COOR: [145.0, 116.0, 75.50] # [cx, cy, r]
  PLOT_SIZE: [ 49,60 ] #[20,25] #[49,60]
  THRESHOLD_MULTUPLIER: 5 # lower this value to find more hot pixels. Values between 5 and 20 work well.
  LOCAL: True
ROI:
  N_LINES: 3
  LINE_WIDTHS: [2,5]
  N_CIRCLES: 3
  #CIRCLES_RADIUS: [5,10,20]
  CIRCLES_RADIUS: [1,2,3,4,5]

TEST:

  BATCH_SIZE: 4
  CUDA: False
  MODEL_WEIGHTS: 'weights/segmentation/130_segmentor.tar'


TRAINING:

  ONLY_SAVE_FEATURES: False
  MODEL: 'unet-efficient'
  MODEL_DIR: 'models_effnet0_features/'
  SAVE_MODEL_STEP: 10
  AUGMENTATION: True

  LOSS: 'bce'

  EXPERIMENT_NAME: 'dislocations_segmentation_effnet-b0'
  TRAINING_SET: 'dislocations' # possible 'us3d', 'dislocations'
  NUM_CHANNELS: 1

  NUM_WORKERS: 4
  PIN_MEMORY: True

  RESUME: ''
  START_EPOCH: 0
  EPOCHS: 150

  BATCH_SIZE: 2
  TEST_BATCH_SIZE: 2

  BASE_LR: 0.001
  LR_DECAY: 1e-6
  MOMENTUM: 0.9

  W_DECAY: 1e-4
  OPTIMIZER: 'Adam'

  AUG: False

  CUDA: False
  GPU_ID: 1

  SEED: 42

LOGGING:

  ENABLE_LOGGING: True
  LOG_DIR: 'logs_effnet0_features/'
  LOG_INTERVAL: 1
